import { Injectable } from '@angular/core';

interface Quiz{
    question: string;
    answer: { option: string, correct: boolean } [];
}

@Injectable({
  providedIn: 'root'
})
export class QuizService {
  quizzes: Quiz[] = [
    {
      question: 'Who is known as father of Java Programming Language',
      answer: [
        { option: 'James Gosling', correct: true },
        { option: 'M. P Java', correct: false },
        { option: 'Charel Babbage', correct: false },
        { option: 'Blais Pascal', correct: false },
      ]
    },
    {
      question: 'In java control statements break, continue, return, try-catch-finally and assert belongs to?',
      answer: [
        { option: 'Selection statements', correct: false },
        { option: 'Loop Statements', correct: false },
        { option: 'Transfer statements', correct: true },
        { option: 'Pause Statement', correct: false },
      ]
    },
    {
      question: 'Which provides runtime environment for java byte code to be executed?',
      answer: [
        { option: 'JDK', correct: false },
        { option: 'JVM', correct: true },
        { option: 'JRED', correct: false },
        { option: 'JAVAC', correct: false }
      ]
    },
    {
      question: 'What is byte code in Java?',
      answer: [
        { option: 'Code generated by a Java compiler', correct: true },
        { option: 'Code generated by a Java Virtual Machine', correct: false },
        { option: 'Name of Java source code file', correct: false },
        { option: 'Block of code written inside a class', correct: false }
      ]
    },
    {
      question: 'Which of the following are not Java keywords?',
      answer: [
        { option: 'double', correct: false },
        { option: 'switch', correct: false },
        { option: 'then', correct: true },
        { option: 'instanceof', correct: false }
      ]
    },
    {
      question: 'Which of these have highest precedence?',
      answer: [
        { option: '()', correct: true },
        { option: '++', correct: false },
        { option: '*', correct: false },
        { option: '>>', correct: false }
      ]
    },
    {
      question: 'Which of these is returned by operator \'&\' ?',
      answer: [
        { option: 'Integer', correct: false },
        { option: 'Character', correct: true },
        { option: 'Boolean', correct: false },
        { option: 'Float', correct: false }
      ]
    },
    {
      question: 'Data type long literals are appended by _____',
      answer: [
        { option: 'Uppercase L', correct: false },
        { option: 'Lowercase l', correct: false },
        { option: 'Long', correct: false },
        { option: 'Both A and B', correct: true },
      ]
    },
    {
      question: 'Java language was initially called as ________',
      answer: [
        { option: 'Sumatra', correct: false },
        { option: 'J++ ', correct: false },
        { option: 'Oak', correct: true },
        { option: 'Pine', correct: false }
      ]
    },
    {
      question: 'Which one is a template for creating different objects ?',
      answer: [
        { option: 'An Array', correct: false },
        { option: 'A class', correct: true },
        { option: 'Interface', correct: false },
        { option: 'Method', correct: false }
      ]
    }
  ]



  getQuizzes(){
    return this.quizzes;
  }
}
